apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: employment-gw-virtualservice
  labels:
    service: employment-gw-virtualservice
spec:
  host:
    - {{ .Values.service.name }}.{{ .Release.Namespace }}.{{ .Values.jxRequirements.ingress.domain }}
  gateways:
    - knative-serving/cluster-local-gateway
    - knative-serving/knative-ingress-gateway
  http:
    - match:
        - uri:
            prefix: /services/dummy/
      rewrite:
        authority: {{ .Values.service.name }}.{{ .Release.Namespace }}.{{ .Values.jxRequirements.ingress.domain }}
        uri: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      rewrite:
        authority: {{ .Values.service.name }}.{{ .Release.Namespace }}.{{ .Values.jxRequirements.ingress.domain }}
        uri: /
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
