apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-employment
type: Opaque
data:
  secret: T1RWbVptRTRObVJqTVRKa09UWTRPVFF6WkdabVltUXlOVEl4WlRKalkyWXlaamN5WkRCbVpqVmhObVpqWmpNMU5UVTRZMlpqWXpRM056TmtaVEZrWm1VMU16YzVNVFEzTVRsbVlXSmpNREkwWlRSaU0yWTBNRGN5WmprM01qUmxaR1l6WWc9PQ==
